image: gitpod/workspace-full

tasks:
  - init: |
      # Install Ionic CLI
      npm install -g @ionic/cli

      # Create a new Ionic project
      ionic start myApp blank --no-deps

      # Navigate to the project directory
      cd myApp

      # Install dependencies
      npm install

      # Allow navigation to your domain
      echo "<allow-navigation href='https://dash.ptero-maker.my.id/*' />" >> config.xml
      echo "<allow-intent href='https://dash.ptero-maker.my.id/*' />" >> config.xml

      # Add CORS support to your API if needed
      # You may need to configure your backend to handle CORS properly.

      # Install the Cordova plugin for CORS (if required)
      # Uncomment the following line if you need to use Insecure HTTP (not recommended for production)
      # ionic cordova plugin add cordova-plugin-whitelist

  - command: |
      # Run the Ionic app
      cd myApp
      ionic serve --host=0.0.0.0 --port=3000

ports:
  - port: 3000
    onOpen: open-preview
