image: gitpod/workspace-full

tasks:
  - init: |
      # Update package manager and install required packages
      sudo apt update
      sudo apt install -y unzip wget

      # Download Android Command Line Tools
      wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O commandlinetools.zip
      mkdir -p $HOME/Android/Sdk/cmdline-tools
      unzip commandlinetools.zip -d $HOME/Android/Sdk/cmdline-tools
      rm commandlinetools.zip

      # Set up environment variables
      echo 'export ANDROID_HOME=$HOME/Android/Sdk' >> ~/.bashrc
      echo 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin' >> ~/.bashrc
      echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> ~/.bashrc
      source ~/.bashrc

      # Install required Android build tools
      sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"

      # Install Cordova
      npm install -g cordova
