image: gitpod/workspace-full

tasks:
  - init: |
      # Update package manager and install Android SDK
      sudo apt update
      sudo apt install -y android-sdk

      # Set up environment variables
      echo 'export ANDROID_HOME=/usr/lib/android-sdk' >> ~/.bashrc
      echo 'export PATH=$PATH:$ANDROID_HOME/tools/bin' >> ~/.bashrc
      echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> ~/.bashrc
      source ~/.bashrc

      # Install required Android build tools
      sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"

      # Install Cordova
      npm install -g cordova
